/// @file view_alternate_account_screen.dart
/// @description Screen for viewing alternate user account information, including levels, points, and badges.
/// @note Core logic and UI structure generated by Google Gemini CLI on 2026-03-09.
/// @author [Jackson]
/// @date 2026-03-09
library;

import 'package:flutter/material.dart';
import 'package:identiflora/database_utils.dart';
import 'package:identiflora/user_data/point_utils.dart';
import 'package:identiflora/user_data/badge_utils.dart';
import 'package:identiflora/widgets/neon_widgets.dart';
import 'view_account_utils.dart';

class ViewAlternateAccountScreen extends StatelessWidget {
  final String username;
  final int points;
  final int numFriends;
  final String displayedBadgeFilePath;

  const ViewAlternateAccountScreen({
    super.key,
    required this.username,
    required this.points,
    required this.numFriends,
    required this.displayedBadgeFilePath,
  });

  @override
  Widget build(BuildContext context) {
    final MapEntry<int, List<int>> levelData = calculateAccountLevel(points);
    final int playerLevel = levelData.key;
    final double normalizedPlayerPoints = normalize(
      levelData.value[1].toDouble(),
      0,
      levelData.value[0].toDouble(),
    );

    final List<LevelBadge> badges = [
      LevelBadge(imagePath: 'assets/badge/seed_badge.png', unlockAtLevel: 5),
      LevelBadge(imagePath: 'assets/badge/sprout_badge.png', unlockAtLevel: 10),
      LevelBadge(
        imagePath: 'assets/badge/sapling_badge.png',
        unlockAtLevel: 15,
      ),
      LevelBadge(imagePath: 'assets/badge/tree_badge.png', unlockAtLevel: 20),
    ];

    return Scaffold(
      appBar: AppBar(title: const Text('Account')),
      body: Center(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            ProgressAvatar(
              normalizedPlayerPoints: normalizedPlayerPoints,
              imagePath: displayedBadgeFilePath,
            ),

            Padding(
              padding: const EdgeInsets.only(top: 8.0),
              child: playerLevel == levelData.value[3]
                  ? const Text("Max level reached!")
                  : levelData.value[0] - levelData.value[1] == 1
                  ? Text("1 more point until level ${playerLevel + 1}!")
                  : Text("${levelData.value[1]}/${levelData.value[0]}"),
            ),

            Text(username, style: const TextStyle(fontSize: 30.0)),

            Padding(
              padding: const EdgeInsets.symmetric(vertical: 8.0),
              child: NeonOutlinedButton(
                onPressed: () async {
                  try {
                    await addFriendRaw(friendUsername: username);
                    if (context.mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text("Added $username"),
                          backgroundColor: Theme.of(
                            context,
                          ).colorScheme.primary,
                        ),
                      );
                    }
                  } catch (e) {
                    if (context.mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        SnackBar(
                          content: Text("Failed to add friend: $e"),
                          backgroundColor: Colors.red,
                        ),
                      );
                    }
                  }
                },
                labelText: "Add Friend",
              ),
            ),

            Padding(
              padding: const EdgeInsets.all(16.0),
              child: NeonContainer(
                width: 350,
                height: 7,
                backgroundColor: Theme.of(context).colorScheme.secondary,
              ),
            ),

            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                TappableMetric(
                  numericValue: playerLevel,
                  category: "Level",
                  onTap: () {
                    debugPrint("Level metric pressed");
                  },
                ),
                TappableMetric(
                  numericValue: points,
                  category: "Points",
                  onTap: () {
                    debugPrint("Points metric pressed");
                  },
                ),
                TappableMetric(
                  numericValue: numFriends,
                  category: "Friends",
                  onTap: () {
                    debugPrint("Friends metric pressed");
                  },
                ),
              ],
            ),

            const Padding(
              padding: EdgeInsets.all(12.0),
              child: Text("Badges", style: TextStyle(fontSize: 20.0)),
            ),

            Padding(
              padding: const EdgeInsets.symmetric(
                horizontal: 32.0,
                vertical: 2.0,
              ),
              child: Divider(
                height: 0.5,
                thickness: 0.5,
                color: Theme.of(context).colorScheme.inverseSurface,
              ),
            ),

            Expanded(
              child: BadgesDisplay(
                badges: badges,
                playerLevel: playerLevel,
                isReadOnly: true,
                selectedBadge: displayedBadgeFilePath,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
